
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_LEDS_DEVICE_ID,
		XPAR_AXI_GPIO_LEDS_BASEADDR,
		XPAR_AXI_GPIO_LEDS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_LEDS_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_RESETS_DEVICE_ID,
		XPAR_AXI_GPIO_RESETS_BASEADDR,
		XPAR_AXI_GPIO_RESETS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_RESETS_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_RPI_ENABLE_DEVICE_ID,
		XPAR_AXI_GPIO_RPI_ENABLE_BASEADDR,
		XPAR_AXI_GPIO_RPI_ENABLE_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_RPI_ENABLE_IS_DUAL
	}
};


